### ISSUE TITLE
Error at import at garmin connect

### ISSUE THREAD

**Issue by harrykl** [simonkrenger/apple-health-to-fitbit#2]
When I try to Import the generated file I get an "Error while uploading the data" permanently.
I tried to upload only one day and several data Formats at Garmin.

[fitbt_format_20190819.txt](https://github.com/simonkrenger/apple-health-to-fitbit/files/3519096/fitbt_format_20190819.txt)

**Comment by simonkrenger** [comment]
Hello @harrykl

Thank you for raising this issue.

I can confirm that I can reproduce the issue that you are describing. However, even when I try to import a legitimate CSV file from fitbit.com I get the same error. So it seems that there is an issue with the import functionality of Garmin Connect.

It seems that other people also have this issue: https://forums.garmin.com/apps-software/mobile-apps-web/f/garmin-connect-web/163622/an-error-occurred-with-your-upload-please-try-again

I have contacted Garmin Support with the issue and hope to get an answer. Sorry that I cannot help you any further, but it seems the problem is on Garmins side at the moment.

Kind regards,
Simon

**Comment by simonkrenger** [comment]
Here is the format I am using to test the upload

```
Activities
Date,Calories Burned,Steps,Distance,Floors,Minutes Sedentary,Minutes Lightly Active,Minutes Fairly Active,Minutes Very Active,Activity Calories
"01-01-2019","0","11","0.01","0","0","0","0","0","0"
"02-01-2019","0","13,666","10.4","0","0","0","0","0","0"
"03-01-2019","0","6,901","5.78","0","0","0","0","0","0"
```

During upload, choose the following settings:
- Language: English
- Length Units: Centimeters, Meters, Kilometers
- Weight Units: Kilograms
- Date Format: 31-12-2019
- Number Format: 1,234.56

**Comment by simonkrenger** [comment]
I have not heard back from you, therefore closing this issue.
